language: php
php:
  - 7.0
  - 7.1
  - nightly

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor

install:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' && $TRAVIS_PHP_VERSION != hhv* ]]; then
        # disable xdebug for performance reasons when code coverage is not needed. note: xdebug on hhvm is disabled by default
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  
  # core framework:
  - composer install --prefer-dist --no-interaction

before_script:

  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
  - ffmpeg -version

  # initialize databases
  - mysql -e 'CREATE DATABASE `vps_tools_test`;';
  - mysql -e "CREATE USER 'vps_tools_test'@'localhost' IDENTIFIED BY '123';";
  - mysql -u root -e "GRANT ALL ON vps_tools_test.* TO 'vps_tools_test'@'localhost';";

  # copy db.php
  - cp tests/config/db.default.php tests/config/db.php

script:
  # validate composer.json
  - composer validate --no-check-lock
  # run PHPUnit
  - vendor/phpunit/phpunit/phpunit --configuration tests/phpunit.xml --stderr